name: Check format and build
on: [push]
jobs:
  check_format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
  test:
    name: Run the tests
    runs-on: ubuntu-latest
    steps:
      - run: "sudo apt-get update -y && sudo apt-get install -y xvfb"
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
